### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by avivace** [sulsadood/MineBoyAdvance#1]
Hey! Thanks for the submission to the GBAJam22. It looks like a proper LICENSE is missing from the repository. Please make sure you add one before the submission deadline for your entry to be eligible for the OSS prizes ;)

If you need more information about choosing a license, check https://choosealicense.com/

**Comment by sulsadood** [comment]
I put a text file named COPYING in it with the license text in it. It looked like it was showing up properly on github when i looked at it yesterday.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Antonio Vivace ***@***.***>
Sent: Saturday, October 29, 2022 11:37:40 AM
To: sulsadood/MineBoyAdvance ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sulsadood/MineBoyAdvance] LICENSE is missing (Issue #1)


Hey! Thanks for the submission to the GBAJam22. It looks like a proper LICENSE is missing from the repository. Please make sure you add one before the submission deadline for your entry to be eligible for the OSS prizes ;)

If you need more information about choosing a license, check https://choosealicense.com/

**Comment by avivace** [comment]
Ooops, sorry - you are right. I was specifically looking for file named LICENSE. Sorry for the noise!
